# netlify.toml
[build]
  # Comando para construir tu proyecto React
  command = "npm run build"
  # Carpeta que Netlify usará para publicar el sitio
  publish = "frontend/build"

[build.environment]
  # Fijamos la versión de Node para evitar errores EBADENGINE
  NODE_VERSION = "18"
